//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApp.CalculatorService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost:3591/CalculatorWebService/", ConfigurationName="CalculatorService.CalculatorWebServiceSoap")]
    public interface CalculatorWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:3591/CalculatorWebService/Add", ReplyAction="*")]
        int Add(int firstNumber, int secondNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:3591/CalculatorWebService/Sub", ReplyAction="*")]
        int Sub(int firstNumber, int secondNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:3591/CalculatorWebService/Div", ReplyAction="*")]
        int Div(int firstNumber, int secondNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:3591/CalculatorWebService/Mult", ReplyAction="*")]
        int Mult(int firstNumber, int secondNumber);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CalculatorWebServiceSoapChannel : TestWebApp.CalculatorService.CalculatorWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculatorWebServiceSoapClient : System.ServiceModel.ClientBase<TestWebApp.CalculatorService.CalculatorWebServiceSoap>, TestWebApp.CalculatorService.CalculatorWebServiceSoap {
        
        public CalculatorWebServiceSoapClient() {
        }
        
        public CalculatorWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculatorWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Add(int firstNumber, int secondNumber) {
            return base.Channel.Add(firstNumber, secondNumber);
        }
        
        public int Sub(int firstNumber, int secondNumber) {
            return base.Channel.Sub(firstNumber, secondNumber);
        }
        
        public int Div(int firstNumber, int secondNumber) {
            return base.Channel.Div(firstNumber, secondNumber);
        }
        
        public int Mult(int firstNumber, int secondNumber) {
            return base.Channel.Mult(firstNumber, secondNumber);
        }
    }
}
